version: '3.9'
services:
  battlon-backend: 
    image: battlon-backend:latest
    container_name: battlon-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt
